### ISSUE TITLE
Error: duplicate value for resource 'attr/orientation' with config ''

### ISSUE THREAD

**Issue by BenjyTec** [rcketscientist/ToggleButtons#11]
I am getting this error when converting my whole project to androidx:
`\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1612: error: duplicate value for resource 'attr/orientation' with config ''.`

It seems like the attribute name 'orientation' in your library is clashing with an attribute in the android library with the same name. If I got this correctly, this can be resolved by renaming this attribute inside your library in library/src/main/res/values/attrs.xml line 10:
`        <attr name="orientation" />`

**Comment by rcketscientist** [comment]
I recall this error, but it should be solved, since I'm currently using
it.  Let me dig and see what I did.

**Comment by rcketscientist** [comment]
I'm on travel and my work laptop is blocking Android devices unfortunately, so I'll throw two blind possibilities.

Are you on 3.0.1?
Are you using `app:orientation`?

**Comment by BenjyTec** [comment]
Yes, I am using 3.0.1 of your library. And yes, inside the  <android.support.v7.widget.ToggleGroup /> I got the attribute `app:orientation="horizontal"`

Thanks for the quick response!

**Comment by rcketscientist** [comment]
Ok I'll follow up in a week or if I can get this darn laptop to host an Android device.

**Comment by BenjyTec** [comment]
Any findings/ideas so far?

**Comment by rcketscientist** [comment]
Thanks for the bump, forgot about this with the holidays. If the sample
doesn't produce this could you link a minimal repro project so I can bang
on this? Thanks.

On Jan 7, 2019 16:33, "BenjyTec" <notifications@github.com> wrote:

Any findings/ideas so far?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/rcketscientist/ToggleButtons/issues/11#issuecomment-452089660>,
or mute the thread

**Comment by BenjyTec** [comment]
Sorry for the delay. I created a new GitLab repo with a minimal sample app. Still, the compilation fails. I hope this will help you to tear down the issue, If there are any other things you need, let me know.
Link to GitLab: https://gitlab.com/BenjyTec/togglebuttons-sample.git

Once again, here the full error log:
```
Android resource compilation failed
Output:  C:\Users\Benni\AndroidStudioProjects\ToggleSample\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1319: error: duplicate value for resource 'attr/orientation' with config ''.
C:\Users\Benni\AndroidStudioProjects\ToggleSample\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1319: error: resource previously defined here.

Command: C:\Users\Benni\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\bfa50a7d83061a2f592339f21805ab7f\aapt2-3.2.0-4818971-windows\aapt2.exe compile --legacy \
        -o \
        C:\Users\Benni\AndroidStudioProjects\ToggleSample\app\build\intermediates\res\merged\debug \
        C:\Users\Benni\AndroidStudioProjects\ToggleSample\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0
```

**Comment by rcketscientist** [comment]
Thanks I'll take a look today.

**Comment by rcketscientist** [comment]
Wow, didn't realize it happened without using the widget. The sample still
works, so it's clearly your updated androidx. As silly as the repro app
was, it helped, thanks. I'll have to dig into the androidx changes. The
widget has to live in pseudo Google land to use some private classes, but
we can at least namespace it out. I was hoping Google would scoop this up
at some point since the old widget is horrendous, so I kept it aligned to
asop as much as possible. However, it does run this risk.

**Comment by rcketscientist** [comment]
Turns out it's a known bug in constraintlayout 2.0 alpha 3.  It's fixed in alpha 4, you just need to use 2 until 4 is out.

https://issuetracker.google.com/issues/121395935
